runtime: python311
entrypoint: gunicorn -b :$PORT run:app

handlers:
  # Serve static files from the parklandapp/static directory
  - url: /static
    static_dir: parklandapp/static

  # Route all other requests to the application
  - url: /.*
    script: auto
