runtime: python311
instance_class: F1
entrypoint: gunicorn -b :$PORT run:app

handlers:
  # Serve static files from the parklandapp/static directory
  - url: /static
    static_dir: parklandapp/static

  # Route all other requests to the application
  - url: /.*
    script: auto

env_variables:
  GOOGLE_CLIENT_ID: "475871163164-7890sm6jo92duupbbg9h1vam0f7lbj3l.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  SECRET_KEY: "txe9zAtxf1tx053txd4Etxe0tx87Etxb4txa7:tx9676txfetxaftxf8tx98txdetxadtxeatx89btxe1B"

automatic_scaling:
  max_instances: 10